#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Connect using xfreerdp to MUTAZUAY rdp
##?
##? Usage:
##?    rdp_connect
docs::parse "$@"

declare -r USERNAME="rpalacios"

function notify() {
	if [ "$(command -v notify-send)" ]; then
		notify-send "$1" "$2"
	fi
}

notify $(basename "$0") 'Establishing RDP connection'
echo $USERNAME
#PASSWORD=$(read -sp "Ingrese la contraseña: ")
#sudo xfreerdp /multimon /floatbar /u:$USERNAME /v:10.100.45.12 /p:$PASSWORD
xfreerdp /multimon /floatbar /u:$USERNAME /v:10.100.45.12
#freerdp-nightly/bin/xfreerdp \ -window-drag \ -menu-anims \ -themes \ +fonts \ /bpp:32 \ /f \ -decorations \ -compression \ /audio-mode:0 \ /mic:format:1 \ /sound:latency:50 \ /multimon \ -floatbar \ /v:$1 \ /u:$2 \ /p:$3

notify $(basename "$0") "RDP connection to MUTAZUAY established!"
